package symbol

var axisT5 = AxisInformation{
	"Insp_mat!": Axis{
		X:            "Fuel_map_xaxis!",
		Y:            "Fuel_map_yaxis!",
		Z:            "Insp_mat!",
		XDescription: "MAP",
		YDescription: "RPM",
		ZDescription: "VE table",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"Batt_korr_tab!": Axis{
		X:            "",
		Y:            "",
		Z:            "Batt_korr_tab!",
		XDescription: "",
		YDescription: "",
		ZDescription: "Injector dead time table",
		XFrom:        "",
		YFrom:        "Batt_volt",
	},
	"Tryck_mat!": Axis{
		X:            "Pwm_ind_trot!",
		Y:            "Pwm_ind_rpm!",
		Z:            "Tryck_mat!",
		XDescription: "Throttle",
		YDescription: "Rpm",
		ZDescription: "Boost",
		XFrom:        "Medeltrot",
		YFrom:        "Rpm",
	},
	"Tryck_mat_a!": Axis{
		X:            "Pwm_ind_trot!",
		Y:            "Pwm_ind_rpm!",
		Z:            "Tryck_mat_a!",
		XDescription: "Throttle",
		YDescription: "Rpm",
		ZDescription: "Boost",
		XFrom:        "Medeltrot",
		YFrom:        "Rpm",
	},
	"Ign_map_0!": Axis{
		X:            "Ign_map_0_x_axis!",
		Y:            "Ign_map_0_y_axis!",
		Z:            "Ign_map_0!",
		XDescription: "MAP",
		YDescription: "RPM",
		ZDescription: "Normal ignition map",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"Ign_map_1!": Axis{
		X:            "Ign_map_1_x_axis!",
		Y:            "Ign_map_1_y_axis!",
		Z:            "Ign_map_1!",
		XDescription: "MAP",
		YDescription: "RPM",
		ZDescription: "Normal ignition map",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"P_fors!": Axis{
		X:            "Reg_last!",
		Y:            "Reg_varv!",
		Z:            "P_fors!",
		XDescription: "Pressure Error",
		YDescription: "Rpm",
		ZDescription: "P-Gain",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"P_fors_a!": Axis{
		X:            "Reg_last!",
		Y:            "Reg_varv!",
		Z:            "P_fors_a!",
		XDescription: "Pressure Error",
		YDescription: "Rpm",
		ZDescription: "P-Gain",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"I_fors!": Axis{
		X:            "Reg_last!",
		Y:            "Reg_varv!",
		Z:            "I_fors!",
		XDescription: "Pressure Error",
		YDescription: "Rpm",
		ZDescription: "I-Gain",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"I_fors_a!": Axis{
		X:            "Reg_last!",
		Y:            "Reg_varv!",
		Z:            "I_fors_a!",
		XDescription: "Pressure Error",
		YDescription: "Rpm",
		ZDescription: "I-Gain",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"D_fors!": Axis{
		X:            "Reg_last!",
		Y:            "Reg_varv!",
		Z:            "D_fors!",
		XDescription: "Pressure Error",
		YDescription: "Rpm",
		ZDescription: "D-Gain",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"D_fors_a!": Axis{
		X:            "Reg_last!",
		Y:            "Reg_varv!",
		Z:            "D_fors_a!",
		XDescription: "Pressure Error",
		YDescription: "Rpm",
		ZDescription: "D-Gain",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"Reg_kon_mat!": Axis{
		X:            "Pwm_ind_trot!",
		Y:            "Pwm_ind_rpm!",
		Z:            "Reg_kon_mat!",
		XDescription: "Throttle",
		YDescription: "Rpm",
		ZDescription: "BCV Constant",
		XFrom:        "Medeltrot",
		YFrom:        "Rpm",
	},
	"Reg_kon_mat_a!": Axis{
		X:            "Pwm_ind_trot!",
		Y:            "Pwm_ind_rpm!",
		Z:            "Reg_kon_mat_a!",
		XDescription: "Throttle",
		YDescription: "Rpm",
		ZDescription: "BCV Constant",
		XFrom:        "Medeltrot",
		YFrom:        "Rpm",
	},
	"Ign_map_2!": Axis{
		X:            "Ign_map_2_x_axis!",
		Y:            "Ign_map_2_y_axis!",
		Z:            "Ign_map_2!",
		XDescription: "MAP",
		YDescription: "RPM",
		ZDescription: "Ignition knock map",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"Ign_map_4!": Axis{
		X:            "Ign_map_0_x_axis!",
		Y:            "Ign_map_0_y_axis!",
		Z:            "Ign_map_4!",
		XDescription: "MAP",
		YDescription: "RPM",
		ZDescription: "Ignition warmup map",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"Fuel_knock_mat!": Axis{
		X:            "Fuel_knock_xaxis!",
		Y:            "Fuel_map_yaxis!",
		Z:            "Fuel_knock_mat!",
		XDescription: "MAP",
		YDescription: "RPM",
		ZDescription: "Knock fuel map",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"Regl_tryck_fgm!": Axis{
		X:            "",
		Y:            "Pwm_ind_rpm!",
		Z:            "Regl_tryck_fgm!",
		XDescription: "",
		YDescription: "Rpm",
		ZDescription: "Maximum boost in 1st and reverse gear (manual)",
		XFrom:        "",
		YFrom:        "Rpm",
	},
	"Regl_tryck_sgm!": Axis{
		X:            "",
		Y:            "Pwm_ind_rpm!",
		Z:            "Regl_tryck_sgm!",
		XDescription: "",
		YDescription: "Rpm",
		ZDescription: "Maximum boost in 2nd gear (manual)",
		XFrom:        "",
		YFrom:        "Rpm",
	},
	"Regl_tryck_fgaut!": Axis{
		X:            "",
		Y:            "Pwm_ind_rpm!",
		Z:            "Regl_tryck_fgaut!",
		XDescription: "",
		YDescription: "Rpm",
		ZDescription: "Maximum boost in 1st and reverse gear (automatic)",
		XFrom:        "",
		YFrom:        "Rpm",
	},
	"Knock_ref_matrix!": Axis{
		X:            "Ign_map_0_x_axis!",
		Y:            "Ign_map_0_y_axis!",
		Z:            "Knock_ref_matrix!",
		XDescription: "MAP",
		YDescription: "RPM",
		ZDescription: "Knock reference map",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"Knock_lim_tab!": Axis{
		X:            "",
		Y:            "Wait_count_tab!",
		Z:            "Knock_lim_tab!",
		XDescription: "",
		YDescription: "Number of sparks to wait before reducing knock offsets",
		ZDescription: "Maximum allowed knock ignition offset",
		XFrom:        "",
		YFrom:        "Rpm",
	},
	"Idle_rpm_tab!": Axis{
		X:            "",
		Y:            "I_kyl_st!",
		Z:            "Idle_rpm_tab!",
		XDescription: "",
		YDescription: "Coolant temperature",
		ZDescription: "Target idle RPM",
		XFrom:        "",
		YFrom:        "Kyl_temp",
	},
	"Idle_fuel_korr!": Axis{
		X:            "Idle_st_last!",
		Y:            "Idle_st_rpm!",
		Z:            "Idle_fuel_korr!",
		XDescription: "Load on idle",
		YDescription: "RPM",
		ZDescription: "Idle fuel correction map",
		XFrom:        "P_medel",
		YFrom:        "Rpm",
	},
	"Tryck_vakt_tab!": Axis{
		X:            "",
		Y:            "Pwm_ind_rpm!",
		Z:            "Tryck_vakt_tab!",
		XDescription: "",
		YDescription: "Rpm",
		ZDescription: "Boost limit map (fuel cut)",
		XFrom:        "",
		YFrom:        "Rpm",
	},
	"Eftersta_fak!": Axis{
		X:            "",
		Y:            "Temp_steg!",
		Z:            "Eftersta_fak!",
		XDescription: "",
		YDescription: "Coolant temperature",
		ZDescription: "Enrichment factor for coldstart #1",
		XFrom:        "",
		YFrom:        "Kyl_temp",
	},
	"Eftersta_fak2!": Axis{
		X:            "",
		Y:            "Temp_steg!",
		Z:            "Eftersta_fak2!",
		XDescription: "",
		YDescription: "Coolant temperature",
		ZDescription: "Enrichment factor for coldstart #2",
		XFrom:        "",
		YFrom:        "Kyl_temp",
	},
}

/*
Symbol	Description	X-axis	X-axis description	Y-axis	Y-axis description
Eftersta_fak!	Enrichmentfactor for coldstart #1. Factor is depending on coolantwater temperature.			Temp_steg!	Map-support points used in the most cooling water dependend maps
*/
