package symbol

var T5Types = map[string]uint8{
	"Batt_korr_tab!":    0x00,
	"D_fors_a!":         CHAR,
	"D_fors!":           CHAR,
	"Fuel_knock_mat!":   CHAR,
	"Fuel_knock_xaxis!": CHAR,
	"Fuel_map_xaxis!":   CHAR,
	"I_fors_a!":         CHAR,
	"I_fors!":           CHAR,
	"Ign_map_0!":        SIGNED,
	"Ign_map_1!":        SIGNED,
	"Inj_konst!":        CHAR,
	"Insp_mat!":         CHAR,
	"P_fors_a!":         CHAR,
	"P_fors!":           CHAR,
	"Pwm_ind_rpm!":      0x00,
	"Pwm_ind_trot!":     CHAR,
	"Reg_kon_mat!":      CHAR,
	"Reg_kon_mat_a!":    CHAR,
	"Reg_last!":         CHAR,
	"Regl_tryck_fgm!":   CHAR,
	"Regl_tryck_sgm!":   CHAR,
	"Regl_tryck_fgaut!": CHAR,
	"Tryck_mat_a!":      CHAR,
	"Tryck_mat!":        CHAR,
	"Knock_ref_matrix!": 0x00,
	"Knock_lim_tab!":    0x00,
	"Apc_knock_tab!":    CHAR,
	"I_kyl_st!":         SIGNED | CHAR,
	"Ign_map_1_y_axis!": SIGNED,
	"Idle_st_last!":     CHAR,
	"Idle_fuel_korr!":   CHAR,
	"Tryck_vakt_tab!":   CHAR,
	"Eftersta_fak!":     CHAR,
	"Eftersta_fak2!":    CHAR,
	"Temp_steg!":        CHAR,
	"Kyltemp_steg!":     CHAR,
	"Kyltemp_tab!":      CHAR,
}

var T5Offsets = map[string]float64{
	"Fuel_knock_mat!":   0.5,
	"Fuel_knock_xaxis!": -1,
	"Fuel_map_xaxis!":   -1,
	"Ign_map_0_x_axis!": -1,
	"Ign_map_2_x_axis!": -1,
	"Insp_mat!":         0.5,
	"Tryck_mat_a!":      -1,
	"Tryck_mat!":        -1,
	"Tryck_vakt_tab!":   -1,
	"Regl_tryck_fgm!":   -1,
	"Regl_tryck_sgm!":   -1,
	"Regl_tryck_fgaut!": -1,
	"Idle_st_last!":     -1,
	"Idle_fuel_korr!":   0.5,
	"Eftersta_fak!":     1.0,
	"Eftersta_fak2!":    1.0,
	//"Temp_steg!":        -40,
}
