package symbol

var axisT8 = AxisInformation{
	"AirCtrlCal.RegMap": Axis{
		"AirCtrlCal.SetLoadXSP",
		"BstKnkCal.n_EngYSP",
		"AirCtrlCal.RegMap",
		"mg/c",
		"rpm",
		"% PWM",
		"AirMassMast.m_Request",
		"ActualIn.n_Engine",
	},
	"AirCtrlCal.Ppart_BoostMap": Axis{
		"AirCtrlCal.PIDXSP",
		"AirCtrlCal.PIDYSP",
		"AirCtrlCal.Ppart_BoostMap",
		"mg/c error",
		"rpm",
		"",
		"AirDIFF",
		"ActualIn.n_Engine",
	},
	"AirCtrlCal.Ipart_BoostMap": Axis{
		"AirCtrlCal.PIDXSP",
		"AirCtrlCal.PIDYSP",
		"AirCtrlCal.Ipart_BoostMap",
		"mg/c error",
		"rpm",
		"",
		"AirDIFF",
		"ActualIn.n_Engine",
	},
	"AirCtrlCal.Dpart_BoostMap": Axis{
		"AirCtrlCal.PIDXSP",
		"AirCtrlCal.PIDYSP",
		"AirCtrlCal.Dpart_BoostMap",
		"mg/c error",
		"rpm",
		"",
		"AirDIFF",
		"ActualIn.n_Engine",
	},
	"BstKnkCal.MaxAirmass": Axis{
		"BstKnkCal.fi_offsetXSP", //BioPower
		"BstKnkCal.n_EngYSP",
		"BstKnkCal.MaxAirmass",
		"° ignition retard (Ioff)",
		"rpm",
		"mg/c",
		"IgnMastProt.fi_Offset",
		"ActualIn.n_Engine",
	},
	"BstKnkCal.MaxAirmassAu": Axis{
		"BstKnkCal.fi_offsetXSP", //BioPower
		"BstKnkCal.n_EngYSP",
		"BstKnkCal.MaxAirmassAu",
		"° ignition retard (Ioff)",
		"rpm",
		"mg/c",
		"IgnMastProt.fi_Offset",
		"ActualIn.n_Engine",
	},
	"IgnAbsCal.fi_NormalMAP": Axis{
		"IgnAbsCal.m_AirNormXSP",
		"IgnAbsCal.n_EngNormYSP",
		"IgnAbsCal.fi_NormalMAP",
		"mg/c",
		"rpm",
		"ign",
		"MAF.m_AirInlet",
		"ActualIn.n_Engine",
	},
	"IgnAbsCal.fi_lowOctanMAP": Axis{
		"IgnAbsCal.m_AirNormXSP",
		"IgnAbsCal.n_EngNormYSP",
		"IgnAbsCal.fi_lowOctanMAP",
		"mg/c",
		"rpm",
		"ign",
		"MAF.m_AirInlet",
		"ActualIn.n_Engine",
	},
	"IgnAbsCal.fi_highOctanMAP": Axis{
		"IgnAbsCal.m_AirNormXSP",
		"IgnAbsCal.n_EngNormYSP",
		"IgnAbsCal.fi_highOctanMAP",
		"mg/c",
		"rpm",
		"ign",
		"MAF.m_AirInlet",
		"ActualIn.n_Engine",
	},
	"BFuelCal.LambdaOneFacMap": Axis{
		"BFuelCal.AirXSP",
		"BFuelCal.RpmYSP",
		"BFuelCal.LambdaOneFacMap",
		"mg/c",
		"rpm",
		"fac",
		"MAF.m_AirInlet",
		"ActualIn.n_Engine",
	},
	"BFuelCal.TempEnrichFacMap": Axis{
		"BFuelCal.AirXSP",
		"BFuelCal.RpmYSP",
		"BFuelCal.TempEnrichFacMap",
		"mg/c",
		"rpm",
		"fac",
		"MAF.m_AirInlet",
		"ActualIn.n_Engine",
	},
	"FFFuelCal.TempEnrichFacMAP": Axis{
		"BFuelCal.AirXSP",
		"BFuelCal.RpmYSP",
		"FFFuelCal.TempEnrichFacMAP",
		"mg/c",
		"rpm",
		"fac",
		"MAF.m_AirInlet",
		"ActualIn.n_Engine",
	},
	"AirCtrlCal.AirmassLimiter": Axis{
		"",
		"",
		"AirCtrlCal.AirmassLimiter",
		"",
		"",
		"mg/c",
		"",
		"",
	},
	"AirCtrlCal.ST_BoostEnable": Axis{
		"",
		"",
		"AirCtrlCal.ST_BoostEnable",
		"",
		"",
		"",
		"",
		"",
	},
	"BoostAdapCal.ST_enable": Axis{
		"",
		"",
		"BoostAdapCal.ST_enable",
		"",
		"",
		"",
		"",
		"",
	},
	"FrompAdapCal.ST_enable": Axis{
		"",
		"",
		"FrompAdapCal.ST_enable",
		"",
		"",
		"",
		"",
		"",
	},
	"AreaAdapCal.ST_enable": Axis{
		"",
		"",
		"AreaAdapCal.ST_enable",
		"",
		"",
		"",
		"",
		"",
	},
	"InjCorrCal.InjectorConst": Axis{
		"",
		"",
		"InjCorrCal.InjectorConst",
		"",
		"",
		"",
		"",
		"",
	},
	"InjCorrCal.BattCorrTab": Axis{
		"",
		"InjCorrCal.BattCorrSP",
		"InjCorrCal.BattCorrTab",
		"",
		"V",
		"",
		"",
		"",
	},
	"IgnAbsCal.ST_EnableOctanMaps": Axis{
		"",
		"",
		"IgnAbsCal.ST_EnableOctanMaps",
		"",
		"",
		"",
		"",
		"",
	},
	"TrqLimCal.Trq_MaxEngineTab1": Axis{
		"",
		"TrqLimCal.n_EngYSP",
		"TrqLimCal.Trq_MaxEngineTab1",
		"",
		"rpm",
		"Nm",
		"",
		"ActualIn.n_Engine",
	},
	"TrqLimCal.Trq_MaxEngineTab2": Axis{
		"",
		"TrqLimCal.n_EngYSP",
		"TrqLimCal.Trq_MaxEngineTab2",
		"",
		"rpm",
		"Nm",
		"",
		"ActualIn.n_Engine",
	},
	"FFTrqCal.FFTrq_MaxEngineTab1": Axis{
		"",
		"TrqLimCal.n_EngYSP",
		"FFTrqCal.FFTrq_MaxEngineTab1",
		"",
		"rpm",
		"Nm",
		"",
		"ActualIn.n_Engine",
	},
	"FFTrqCal.FFTrq_MaxEngineTab2": Axis{
		"",
		"TrqLimCal.n_EngYSP",
		"FFTrqCal.FFTrq_MaxEngineTab2",
		"",
		"rpm",
		"Nm",
		"",
		"ActualIn.n_Engine",
	},
	"TrqLimCal.Trq_ManGear": Axis{
		"",
		"",
		"TrqLimCal.Trq_ManGear",
		"",
		"8 : 0 1 2 3 4 5 6 8",
		"Nm",
		"",
		"",
	},
	"TrqMastCal.X_AccPedalMAP": Axis{
		X:            "TrqMastCal.n_EngineXSP",
		Y:            "TrqMastCal.Trq_PedYSP",
		Z:            "TrqMastCal.X_AccPedalMAP",
		XDescription: "Rpm",
		YDescription: "Nm",
		ZDescription: "Pedal position map",
		XFrom:        "ActualIn.n_Engine",
		YFrom:        "",
	},
	"TrqMastCal.Trq_NominalMap": Axis{
		X:            "TrqMastCal.m_AirXSP",
		Y:            "TrqMastCal.n_EngineYSP",
		Z:            "TrqMastCal.Trq_NominalMap",
		XDescription: "rpm",
		YDescription: "mg/c",
		ZDescription: "Nm",
		XFrom:        "ActualIn.n_Engine",
		YFrom:        "MAF.m_AirInlet",
	},
	"TrqMastCal.m_AirTorqMap": Axis{
		X:            "TrqMastCal.Trq_EngXSP",
		Y:            "TrqMastCal.n_EngineYSP",
		Z:            "TrqMastCal.m_AirTorqMap",
		XDescription: "Nm",
		YDescription: "Rpm",
		ZDescription: "mg/c",
		XFrom:        "",
		YFrom:        "ActualIn.n_Engine",
	},
	"TrqLimCal.Trq_CompressorNoiseRedLimMAP": Axis{
		X:            "TrqLimCal.CompressorNoiseXSP",
		Y:            "TrqLimCal.CompressorNoiseYSP",
		Z:            "TrqLimCal.Trq_CompressorNoiseRedLimMAP",
		XDescription: "kPa",
		YDescription: "rpm",
		ZDescription: "Nm",
		XFrom:        "",
		YFrom:        "ActualIn.n_Engine",
	},
	"TrqLimCal.Trq_OverBoostTab": Axis{
		X:            "",
		Y:            "TrqLimCal.n_EngYSP",
		Z:            "TrqLimCal.Trq_OverBoostTab",
		XDescription: "",
		YDescription: "rpm",
		ZDescription: "Nm",
		XFrom:        "",
		YFrom:        "ActualIn.n_Engine",
	},
	"TrqLimCal.Trq_MaxEngineAutTab2": Axis{
		X:            "",
		Y:            "TrqLimCal.n_EngYSP",
		Z:            "TrqLimCal.Trq_MaxEngineAutTab2",
		XDescription: "",
		YDescription: "rpm",
		ZDescription: "Nm",
		XFrom:        "",
		YFrom:        "ActualIn.n_Engine",
	},
	"TrqLimCal.Trq_MaxEngineAutTab1": Axis{
		X:            "",
		Y:            "TrqLimCal.n_EngYSP",
		Z:            "TrqLimCal.Trq_MaxEngineAutTab1",
		XDescription: "",
		YDescription: "rpm",
		ZDescription: "Nm",
		XFrom:        "",
		YFrom:        "ActualIn.n_Engine",
	},
	"TrqLimCal.Trq_MaxEngineManTab2": Axis{
		X:            "",
		Y:            "TrqLimCal.n_EngYSP",
		Z:            "TrqLimCal.Trq_MaxEngineManTab2",
		XDescription: "",
		YDescription: "rpm",
		ZDescription: "Nm",
		XFrom:        "",
		YFrom:        "ActualIn.n_Engine",
	},
	"TrqLimCal.Trq_MaxEngineManTab1": Axis{
		X:            "",
		Y:            "TrqLimCal.n_EngYSP",
		Z:            "TrqLimCal.Trq_MaxEngineManTab1",
		XDescription: "",
		YDescription: "rpm",
		ZDescription: "Nm",
		XFrom:        "",
		YFrom:        "ActualIn.n_Engine",
	},
	"KnkFuelCal.EnrichmentMap": Axis{
		X:            "IgnKnkCal.m_AirXSP",
		Y:            "IgnKnkCal.n_EngYSP",
		Z:            "KnkFuelCal.EnrichmentMap",
		XDescription: "mg/c",
		YDescription: "rpm",
		ZDescription: "Fac",
		XFrom:        "MAF.m_AirInlet",
		YFrom:        "ActualIn.n_Engine",
	},
	"InjAnglCal.Map": Axis{
		X:            "InjAnglCal.AirXSP",
		Y:            "InjAnglCal.RpmYSP",
		Z:            "InjAnglCal.Map",
		XDescription: "mg/c",
		YDescription: "rpm",
		ZDescription: "°",
		XFrom:        "MAF.m_AirInlet",
		YFrom:        "ActualIn.n_Engine",
	},
	"BFuelCal.m_AirJerkTab": Axis{
		X:            "",
		Y:            "BFuelCal.RpmYSP",
		Z:            "BFuelCal.m_AirJerkTab",
		XDescription: "",
		YDescription: "rpm",
		ZDescription: "z",
		XFrom:        "",
		YFrom:        "ActualIn.n_Engine",
	},
	"BFuelCal.JerkEnrichFacTab": Axis{
		X:            "",
		Y:            "BFuelCal.RpmYSP",
		Z:            "BFuelCal.JerkEnrichFacTab",
		XDescription: "",
		YDescription: "rpm",
		ZDescription: "z",
		XFrom:        "",
		YFrom:        "ActualIn.n_Engine",
	},
	"IgnAbsCal.fi_IgnMBTMAP": Axis{
		"IgnAbsCal.m_AirMBTXSP",
		"IgnAbsCal.n_EngMBTYSP",
		"IgnAbsCal.fi_IgnMBTMAP",
		"mg/c",
		"rpm",
		"ign",
		"MAF.m_AirInlet",
		"ActualIn.n_Engine",
	},
	"IgnAbsCal.fi_FuelCutMAP": Axis{
		"IgnAbsCal.T_EngFuelCutXSP",
		"IgnAbsCal.n_EngFuelCutYSP",
		"IgnAbsCal.fi_FuelCutMAP",
		"temp",
		"rpm",
		"ign",
		"ActualIn.T_Engine",
		"ActualIn.n_Engine",
	},
	"IgnAbsCal.fi_StartMAP": Axis{
		"IgnAbsCal.T_EngStartXSP",
		"IgnAbsCal.n_EngStartYSP",
		"IgnAbsCal.fi_StartMAP",
		"temp",
		"rpm",
		"ign",
		"ActualIn.T_Engine",
		"ActualIn.n_Engine",
	},
	"PedalMapCal.Trq_RequestMap": Axis{
		X:            "PedalMapCal.n_EngineMap",
		Y:            "PedalMapCal.X_PedalMap",
		Z:            "PedalMapCal.Trq_RequestMap",
		XDescription: "rpm",
		YDescription: "%",
		ZDescription: "Torque request map",
		XFrom:        "ActualIn.n_Engine",
		YFrom:        "",
	},
	"AirCtrlCal.PRatioMaxTab": Axis{
		X:            "",
		Y:            "AirCtrlCal.q_AirInletSP",
		Z:            "AirCtrlCal.PRatioMaxTab",
		XDescription: "",
		YDescription: "g/s",
		ZDescription: "",
		XFrom:        "",
		YFrom:        "",
	},
}
